version: "3.9"
services:
  db:
    image: postgres
    volumes:
      - .db/data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
  app:
    build:
      context: ./fsd
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
        - APPLICATION_UNDER_TEST=True
    depends_on:
      - "db"
  nginx:
    build: 
      context: ./nginx-proxy
      dockerfile: Dockerfile
    depends_on:
      - "app"
    ports:
      - "5051:80"
  test:
    build:
      context: ./tests
      dockerfile: Dockerfile
    depends_on: 
      - "nginx"