# Generated by Django 3.1.4 on 2021-02-06 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annualfullformatted',
            name='cik',
        ),
        migrations.RemoveField(
            model_name='annualfullformatted',
            name='cik2',
        ),
        migrations.RemoveField(
            model_name='annualfullformatted',
            name='cik_count',
        ),
        migrations.RemoveField(
            model_name='annualfullformatted',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='annualfullformatted',
            name='instant_date',
        ),
        migrations.RemoveField(
            model_name='annualfullformatted',
            name='link_count',
        ),
        migrations.RemoveField(
            model_name='annualfullformatted',
            name='report_date',
        ),
        migrations.RemoveField(
            model_name='annualfullformatted',
            name='report_id',
        ),
        migrations.RemoveField(
            model_name='annualfullformatted',
            name='report_type',
        ),
        migrations.RemoveField(
            model_name='annualfullformatted',
            name='sub_industry',
        ),
        migrations.RemoveField(
            model_name='annualfullformatted',
            name='ticker_count',
        ),
        migrations.AlterField(
            model_name='annualfullformatted',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
